blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index),
#    path('about', views.about)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('control.urls')),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
    path('mqtt/', include('mqttWebsocket.urls')),
   
        
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('csregister/', views.CsRegisterView.as_view(), name='csregister'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),
    path('profile/password/', views.password_edit_view, name='password_edit'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.profile_update_view, name='profile_update'),
    path('profile/delete/', views.profile_delete_view, name='profile_delete'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from .choice import *
from django.conf import settings


class UserManager(BaseUserManager):
    def create_user(self, user_id, password, email, hp, name,  department, auth, **extra_fields):
        user = self.model(
            user_id = user_id,
            email = email,
            hp = hp,
            name = name,
            department = department,
            auth = auth,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password, email=None, hp=None, name=None, department=None,  auth=None):
        user = self.create_user(user_id, password, email, hp, name, department, auth)
        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.level = 0
        user.save(using=self._db)
        return user
   
class User(AbstractBaseUser, PermissionsMixin):
    
    objects = UserManager()

    user_id = models.CharField(max_length=17, verbose_name="아이디", unique=True)
    password = models.CharField(max_length=256, verbose_name="비밀번호")
    email = models.EmailField(max_length=128, verbose_name="이메일",null=True, unique=True)
    hp = models.CharField(max_length=20, verbose_name="핸드폰번호", null=True, unique=True)
    name = models.CharField(max_length=8, verbose_name="이름", null=True)
    level = models.CharField(choices=LEVEL_CHOICES, max_length=18, verbose_name="등급", default=3)
    department = models.CharField(choices=DEPARTMENT_CHOICES, max_length=24, verbose_name="서비스 사용자", null=True, blank=True)
    access_ip = models.CharField(max_length=20, verbose_name="접속 IP", null=True, blank=True)
    auth = models.CharField(max_length=10, verbose_name="인증번호", null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일', null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['email']
    
    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "회원목록"
        verbose_name = "사용자"
        verbose_name_plural = "사용자"
   

users/views.py
import json
from urllib import request
from wsgiref.util import request_uri
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from .decorators import *
from .models import User
from django.views.generic import View, CreateView, FormView, View
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from .forms import CsRegisterForm, RecoveryIdForm, RecoveryPwForm,CustomSetPasswordForm, CustomPasswordChangeForm, LoginForm, CustomCsUserChangeForm, CheckPasswordForm
from django.urls import reverse
from .helper import send_mail, email_auth_num
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.conf import settings
from django.core.serializers.json import DjangoJSONEncoder

#로그인
@method_decorator(logout_message_required, name='dispatch')
class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=user_id, password=password)
        
        if user is not None:
            self.request.session['user_id'] = user_id
            login(self.request, user)
            remeber_session = self.request.POST.get('remember_session', False)
            if remeber_session:
                settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
                
        return super().form_valid(form)
    
#로그아웃
def logout_view(request):
    logout(request)
    return redirect('/users/login/')
        

# 회원가입 약관동의
@method_decorator(logout_message_required, name='dispatch')
class AgreementView(View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'users/agreement.html')

    def post(self, request, *args, **kwarg):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True
            if request.POST.get('csregister') == 'csregister':       
                return redirect('/users/csregister/')
            else:
                return redirect('/users/register/')
        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'users/agreement.html')  
        
        
#필로티 이용자 회원가입
class CsRegisterView(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = CsRegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        self.request.session['register_auth'] = True
        messages.success(self.request, '회원님의 입력한 Email 주소로 인증 메일이 발송되었습니다. 인증 후 로그인이 가능합니다.')
        return reverse('users:register_success')

    def form_valid(self, form):
        self.object = form.save()
        
        send_mail(
        '[CNDI]{}님의 회원가입 인증메일 입니다.'.format(self.object.user_id),
        [self.object.email],
        html=render_to_string('users/register_email.html', {
            'user': self.object,
            'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).encode().decode(),
            'domain': self.request.META['HTTP_HOST'],
            'token': default_token_generator.make_token(self.object),
        }),
    )
        return redirect(self.get_success_url())
    
def register_success(request):
    if not request.session.get('register_auth', False):
        raise PermissionDenied
    request.session['register_auth'] = False

    return render(request, 'users/register_success.html')    

# 이메일 인증 활성화
def activate(request, uid64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        current_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        messages.error(request, '메일 인증에 실패했습니다.')
        return redirect('users:login')

    if default_token_generator.check_token(current_user, token):
        current_user.is_active = True
        current_user.save()

        messages.info(request, '메일 인증이 완료 되었습니다. 회원가입을 축하드립니다!')
        return redirect('users:login')

    messages.error(request, '메일 인증에 실패했습니다.')
    return redirect('users:login')

# 아이디찾기
@method_decorator(logout_message_required, name='dispatch')
class RecoveryIdView(View):
    template_name = 'users/recovery_id.html'
    recovery_id = RecoveryIdForm

    def get(self, request):
        if request.method=='GET':
            form_id = self.recovery_id(None)
        return render(request, self.template_name, { 'form_id':form_id, })
    
# 아이디찾기 AJAX 통신
def ajax_find_id_view(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_id = User.objects.get(name=name, email=email)
       
    return HttpResponse(json.dumps({"result_id": result_id.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")

# 비밀번호찾기
@method_decorator(logout_message_required, name='dispatch')
class RecoveryPwView(View):
    template_name = 'users/recovery_pw.html'
    recovery_pw = RecoveryPwForm

    def get(self, request):
        if request.method=='GET':
            form_pw = self.recovery_pw(None)
            return render(request, self.template_name, { 'form_pw':form_pw, })


# 비밀번호찾기 AJAX 통신
def ajax_find_pw_view(request):
    user_id = request.POST.get('user_id')
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_pw = User.objects.get(user_id=user_id, name=name, email=email)

    if result_pw:
        auth_num = email_auth_num()
        result_pw.auth = auth_num 
        result_pw.save()

        send_mail(
            '[CNDI] 비밀번호 찾기 인증메일입니다.',
            [email],
            html=render_to_string('users/recovery_email.html', {
                'auth_num': auth_num,
            }),
        )
    # print(auth_num)
    return HttpResponse(json.dumps({"result": result_pw.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")
 

# 비밀번호찾기 인증번호 확인
def auth_confirm_view(request):
    # if request.method=='POST' and 'auth_confirm' in request.POST:
    user_id = request.POST.get('user_id')
    input_auth_num = request.POST.get('input_auth_num')
    user = User.objects.get(user_id=user_id, auth=input_auth_num)
    # login(request, user)
    user.auth = ""
    user.save()
    request.session['auth'] = user.user_id  
    
    return HttpResponse(json.dumps({"result": user.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")

# 비밀번호찾기 새비밀번호 등록
@logout_message_required
def auth_pw_reset_view(request):
    if request.method == 'GET':
        if not request.session.get('auth', False):
            raise PermissionDenied

    if request.method == 'POST':
        session_user = request.session['auth']
        current_user = User.objects.get(user_id=session_user)
        # del(request.session['auth'])
        login(request, current_user)

        reset_password_form = CustomSetPasswordForm(request.user, request.POST)
        
        if reset_password_form.is_valid():
            user = reset_password_form.save()
            messages.success(request, "비밀번호 변경완료! 변경된 비밀번호로 로그인하세요.")
            logout(request)
            return redirect('users:login')
        else:
            logout(request)
            request.session['auth'] = session_user
    else:
        reset_password_form = CustomSetPasswordForm(request.user)

    return render(request, 'users/password_reset.html', {'form':reset_password_form})  

#비밀번호 수정
@login_message_requred
def password_edit_view(request):
    if request.method == 'POST':
        password_change_form  = CustomPasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "비밀번호를 성공적으로 변경하였습니다.")
            return redirect('users:profile')
        
    else:
        password_change_form = CustomPasswordChangeForm(request.user)
        
    return render(request, 'users/profile_password.html', {'password_change_form':password_change_form})        

#프로필 구현
@login_message_requred
def profile_view(request):
    if request.method =='GET':
        return render(request, 'users/profile.html')
    
#프로필 수정
@login_message_requred
def profile_update_view(request):
    if request.method=='POST':
        user_change_form = CustomCsUserChangeForm(request.POST, instance = request.user)
        
        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return render(request, 'users/profile.html')
        
    else:
        user_change_form = CustomCsUserChangeForm(instance = request.user)
        
        return render(request, 'users/profile_update.html', {'user_change_form':user_change_form})     
    
#회원탈퇴
@login_message_requred
def profile_delete_view(request):
    if request.method == 'POST':
        password_form = CheckPasswordForm(request.user, request.POST)
        
        if password_form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, "회원탈퇴가 완료되었습니다.")

templates/users/login.html
{%extends "user_base.html" %}
{%load static %}

{% block content %}

<!-- Start wrapper-->
 <div id="wrapper">

 <div class="loader-wrapper"><div class="lds-ring"><div></div><div></div><div></div><div></div></div></div>
	<div class="card card-authentication1 mx-auto my-5">
		<div class="card-body">
		 <div class="card-content p-2">
		 	<div class="text-center">
        <br>
		 		<img src="{% static 'images/cndi_bold.png' %}" alt="logo icon">
		 	</div>
       <br>
		  <div class="card-title text-uppercase text-center py-3"  >아이디와 비밀번호 입력을 통해<br> 로그인할 수 있습니다.</div>

		    <form method="POST" action="." novalidate>
              {% csrf_token %}
			  <div class="form-group">
			  <label for="exampleInputUsername" class="sr-only">UserID</label>
			   <div class="position-relative has-icon-right">
          <label name="label_user_id" for="{{ form.user_id.id_for_label }}"><i class="icon-user"></i> {{ form.user_id.label }} </label>
        {{ form.user_id }}
                    <script type="text/javascript">
                        if (document.getElementsByName('user_id')[0].value != '') {
                            document.getElementsByName('label_user_id')[0].setAttribute('class', 'active');
                        }
                    </script>
                    {% if form.user_id.errors %}
                    <script type="text/javascript">
                        document.getElementsByName('user_id')[0].setAttribute('class',
                            'form-control is-invalid')
                    </script>
                    {% for error in form.user_id.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% endif %}
			   </div>
			  </div>
			  <div class="form-group">
			  <label for="exampleInputPassword" class="sr-only">Password</label>
			   <div class="position-relative has-icon-right">
				  <label for="{{ form.password.id_for_label }}"><i class="icon-lock"></i> {{ form.password.label }}</label>
                  {{ form.password }}

                            {% if form.password.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('password')[0].setAttribute('class', 'form-control is-invalid')
                            </script>
                            {% for error in form.password.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
			   </div>
			  </div>
			<div class="form-row">
			 <div class="form-group col-6">

        <!--
			   <div class="icheck-material-white">
                <input type="checkbox" id="user-checkbox" checked="" />
                <label for="user-checkbox">Remember me</label>
			  </div>
        -->
			 </div>
			 <div class="form-group col-6 text-right">
			  <a href="#"></a>
			 </div>
			</div>

			 <button type="submit" class="btn btn-light btn-block" >로그인</button>
			  <div class="text-center mt-3"></div>
			
			 </form>
		   </div>
		  </div>
      {% if not user.is_authenticated %}
		  <div class="card-footer text-center py-3">
		    <p class="text-warning mb-0" style ="font-size:12px;">
          <a href="/users/recovery/id"> 아이디 찾기</a> |
          <a href="/users/recovery/pw"> 비밀번호 찾기</a> |
          <a href="{% url 'users:agreement' %}"> 회원가입</a></p>
		  </div>
      {% endif %}
	     </div>
    
{%endblock%}

templates/users/profile.html
{%extends "base.html" %}
{%load static %}

{% block content %}
<div class="container">
  <div style="margin-top: 5rem !important;">
      <div class="col-12">

          <div class="row justify-content-center">
              <div class="card">
                  <div class="card-header" style="padding-bottom:8px;">
                      <strong style="font-size: 18px;"><i class="fas fa-user-cog"></i>&nbsp;&nbsp;내 정보</strong>
                  </div>
                  <div class="card-body">
                      <table style="color:black; margin-left:10px;">
                          <tr>
                              <td class="profile_title" style="color:#FFFFFFFF">아이디:&nbsp;&nbsp;</td>
                              {% if user.level == '0'%}
                              <td class="profile_content" style="color:#FFFFFFFF">{{ user.user_id }}&nbsp;&nbsp;(개발자)</td>
                              {% elif user.level == '1' %}
                              <td class="profile_content" style="color:#FFFFFFFF">{{ user.user_id }}&nbsp;&nbsp;(관리자)</td>
                              {% else %}
                              <td class="profile_content" style="color:#FFFFFFFF">{{ user.user_id }}</td>
                              {% endif %}
                          </tr>
                          <tr>
                              <td class="profile_title" style="color:#FFFFFFFF">이메일:  </td>
                              <td class="profile_content" style="color:#FFFFFFFF">{{ user.email }}</td>
                          </tr>
                          <tr>
                              <td class="profile_title" style="color:#FFFFFFFF">이름&nbsp;&nbsp; :  </td>
                              <td class="profile_content" style="color:#FFFFFFFF">{{ user.name }}</td>
                          </tr>
                          <tr>
                              <td class="profile_title" style="color:#FFFFFFFF">연락처:  </td>
                              <td class="profile_content" style="color:#FFFFFFFF">0{{ user.hp }}</td>
                          </tr>
                          
                      </table>
  
                      <hr>
                      <div style="text-align: center;">
    
                          <a href="{% url 'users:profile_update' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-edit"></i>&nbsp;내정보수정</a>&nbsp;&middot;&nbsp;
                          <a href="{% url 'users:password_edit' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-lock"></i>&nbsp;비밀번호변경</a>&nbsp;&middot;&nbsp;
                          <a href="{% url 'users:profile_delete' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-slash"></i>&nbsp;회원탈퇴</a> <br>
                          </div>

                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}

templates/users/recovery_pw.html
{%extends "user_base.html" %}
{%load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/loading.css' %}" type="text/css">
{% endblock %}


{% block content %}
<!-- Start wrapper-->
<div id="wrapper">

    <div class="loader-wrapper"><div class="lds-ring"><div></div><div></div><div></div><div></div></div></div>
       <div class="card card-authentication1 mx-auto my-5">
        <div class="card-body">
            <div class="card-content p-2">
                <div class="text-center">
                    <!--<img src="{% static 'images/logo-icon.png' %}" alt="logo icon">
         -->
                </div>
             <div class="card-title text-uppercase text-center py-3" >비밀번호 찾기</div>
                  <div class="row mt-5">
                      <div class="col-12">
                          {% csrf_token %}
                          <!--아이디-->
                          <div class="mb-4 md-form">
                              <label name="label_user_id" for="{{ form_pw.user_id.id_for_label }}"><i
                                  class="icon-user"></i>&nbsp;&nbsp;{{ form_pw.user_id.label }}</label>
                                  {{ form_pw.user_id }}
                          </div>
                          <!--이름-->
                          <div class="mb-4 md-form">
                              <label name="label_name" for="{{ form_pw.name.id_for_label }}"><i
                                  class="fas fa-user-edit"></i>&nbsp;&nbsp;{{ form_pw.name.label }}</label>
                                  {{ form_pw.name }}
                          </div>
                          <!--이메일-->
                          <div class="mb-4 md-form">
                              <label name="label_email" for="{{ form_pw.email.id_for_label }}"><i
                                      class="fa fa-envelope-open-o"></i>&nbsp;&nbsp;{{ form_pw.email.label }}</label>
                                  {{ form_pw.email }}
                              <small class="form-text mt-2" style="color:#FFFFFFBF">
                                  등록하신 메일로 인증번호가 발송됩니다.
                              </small>
                          </div>
                          <!--비밀번호찾기 버튼-->
                          

                          <button id="find_pw" class="btn btn-light btn-block" name="recovery_pw" >비밀번호 찾기</button>
                            <div class="text-center mt-3"></div>

                          <div style="text-align: center; margin-top: 10px; margin-bottom: -10px;">
                              <div id="loading"></div>
                          </div>

                          <div id="result_pw"></div>

                          <br>
                          

                          <div class="card-footer text-center py-3">
                            <p class="text-warning mb-0" style="font-size:13px">아이디를 잊으셨나요?</span>
                                <a href="{% url 'users:recovery_id' %}" style="font-size:13px">아이디찾기</a></p>
                          </div>

                          <script type="text/javascript">
                            $(document).ready(function () {
                                $('#find_pw').click(function () {
                                    $('#loading').replaceWith('<div id="loading_end" class="loading"></div>')
                                    var user_id = $("#pw_form_id").val();
                                    var name = $("#pw_form_name").val();
                                    var email = $("#pw_form_email").val();

                                    $.ajax({
                                        type: "POST",
                                        url: "/users/recovery/pw/find/",
                                        dataType: "json",
                                        data: {
                                            'user_id': user_id,
                                            'name': name,
                                            'email': email,
                                            'csrfmiddlewaretoken': '{{csrf_token}}',
                                        },
                                        success: function (response) {
                                            $('#loading_end').remove()
                                            alert('회원님의 이메일로 인증코드를 발송하였습니다.');
                                            // $('#result_pw').replaceWith('<h5><p id="result_pw">회원님의 비밀번호는 <strong>'+response.result_pw+'</strong> 입니다.</p></h5>')
                                            $('#div_find_pw').remove()
                                            $('#result_pw').replaceWith(
                                                // '<br><form action="{% url "users:recovery_auth" %}" method="POST"><input type="text" name="input_auth_num" placeholder="인증번호를 입력해주세요." class="form-control" /><br><button type="submit" name="auth_confirm" class="btn btn-danger">인증확인</button></form>'
                                                '<hr><div class="row justify-content-md-center"><form class="form-inline" style="margin-bottom:-15px; margin-top:-10px;"><div class="md-form md-outline"><label for="input_auth_num">인증번호 입력 (<span id="timeset"></span>)</label><input type="text" id="input_auth_num" class="form-control mx-sm-2" autofocus/></div></form>'+
                                                  '<button type="submit" name="auth_confirm" id="id_auth_confirm" class="btn btn-light btn-block" style="opacity: 90%; height:30%; margin-top:10px; font-size: 12px;"><i class="fas fa-check"></i>&nbsp;&nbsp;인증확인</button></div>'
                                            )
                                            function countdown( elementName, minutes, seconds ) {
                                                var elementName, endTime, hours, mins, msLeft, time;
                                                function twoDigits( n ) {
                                                    return (n <= 9 ? "0" + n : n);
                                                }
                                                function updateTimer() {
                                                    msLeft = endTime - (+new Date);
                                                    if ( msLeft < 1000 ) {
                                                        alert("인증시간이 초과되었습니다.");
                                                        $("" + elementName).remove();
                                                        cert_ok = false;
                                                        certificationNum = false;
                                                        location.href = "{% url 'users:recovery_pw' %}"
                                                    } else {
                                                        time = new Date( msLeft );
                                                        hours = time.getUTCHours();
                                                        mins = time.getUTCMinutes();
                                                        $("" + elementName).html((hours ? hours + ':' + twoDigits( mins ) : twoDigits(mins))
                                                        + ':' + twoDigits( time.getUTCSeconds()));
                                                        setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
                                                    }
                                                }
                                                endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
                                                updateTimer();
                                            }
                                            countdown("#timeset", 5, 0);

                                            var user = response.result

                                            $(document).ready(function () {
                                                $('#id_auth_confirm').click(function () {
                                                    var input_auth_num = $("#input_auth_num").val();

                                                    $.ajax({
                                                        type: "POST",
                                                        url: "/users/recovery/pw/auth/",
                                                        dataType: "json",
                                                        data: {
                                                            'user_id': user,
                                                            'input_auth_num': input_auth_num,
                                                            'csrfmiddlewaretoken': '{{csrf_token}}',
                                                        },
                                                        success: function (response) {
                                                            // location.href = "/users/profile/password/";
                                                            location.href = "{% url 'users:recovery_pw_reset' %}";
                                                        },
                                                        error: function () {
                                                            if ($('#input_auth_num').val()=="") {
                                                                alert('회원님의 이메일로 전송된 인증번호를 입력해주세요.');
                                                            } else {
                                                                alert('인증번호가 일치하지 않습니다.');
                                                            }
                                                        },
                                                    });
                                                })
                                            })
                                        },
                                        error: function () {
                                            $('#loading_end').remove()
                                            if (user_id == "" || name == "" || email == "") {
                                                alert('아이디, 이름, 이메일을 모두 입력해주세요.');
                                            } else {
                                                alert('입력하신 정보가 일치하지 않거나 존재하지 않습니다.');
                                            }
                                        },
                                    });
                                })
                            });
                        </script>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>    
{% endblock %}